# Generated by Django 5.2.8 on 2025-11-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoriums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('auditorium', models.CharField(max_length=30)),
                ('conclusion', models.TextField(max_length=200)),
                ('priority', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=100)),
                ('standart', models.CharField(choices=[('ISO 9001', 'ISO 9001')], max_length=100)),
            ],
        ),
    ]
