# Generated by Django 5.2.8 on 2025-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auditoriums'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('resultado', models.TextField(max_length=200)),
                ('standart', models.CharField(choices=[('ISO 9001: 2015', 'ISO 9001: 2015')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Auditoriums',
        ),
    ]
