# Generated by Django 5.2.8 on 2025-11-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_observations_delete_auditoriums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observations',
            old_name='resultado',
            new_name='observaciones',
        ),
        migrations.AddField(
            model_name='observations',
            name='staste',
            field=models.CharField(choices=[('Iniciada', 'Iniciada'), ('En curso', 'En curso'), ('Completada', 'Completada'), ('Cerrada', 'Cerrada')], default='Iniciada', max_length=50),
        ),
        migrations.AlterField(
            model_name='observations',
            name='standart',
            field=models.CharField(choices=[('ISO 9001: 2015', 'ISO 9001: 2015')], default='Iniciada', max_length=100),
        ),
    ]
