# Generated by Django 5.2.8 on 2025-11-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_resultado_observations_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observations',
            name='type',
            field=models.CharField(choices=[('No conformidad', 'No conformidad'), ('Observacion', 'Observacion'), ('Oportunidad de mejora', 'Oportunidad de mejora')], default='observaciones', max_length=80),
        ),
    ]
