# Generated by Django 5.2.8 on 2025-12-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_observations_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('Almacen', 'Almacen'), ('Gestion de calidad', 'Gestion de calidad'), ('Control de calidad', 'Control de calidad'), ('Direccion', 'Direccion'), ('Gerencia de productos', 'Gerencia de productos'), ('Informatica y Telecomunicaciones', 'Informatica y Telecomunicaciones'), ('RRHH', 'RRHH'), ('Seguridad y Salud Laboral', 'Seguridad y Salud Laboral'), ('Servicios generales', 'Servicios generales'), ('Ventas y Distribucion', 'Ventas y Distribucion')], max_length=80),
        ),
    ]
