# Generated by Django 5.2.8 on 2026-02-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customuser_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='standart',
            field=models.CharField(choices=[('ISO 9001: 2015', 'ISO 9001: 2015'), ('Norma Covenin', 'Norma Covenin')], default='Iniciada', max_length=100),
        ),
    ]
