# Generated by Django 5.2.8 on 2026-02-23 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_observations_standart'),
    ]

    operations = [
        migrations.AddField(
            model_name='observations',
            name='departament',
            field=models.CharField(choices=[('Almacen', 'Almacen'), ('Gestion de calidad', 'Gestion de calidad'), ('Control de calidad', 'Control de calidad'), ('Direccion', 'Direccion'), ('Gerencia de productos', 'Gerencia de productos'), ('Informatica y Telecomunicaciones', 'Informatica y Telecomunicaciones'), ('RRHH', 'RRHH'), ('Seguridad y Salud Laboral', 'Seguridad y Salud Laboral'), ('Servicios generales', 'Servicios generales'), ('Ventas y Distribucion', 'Ventas y Distribucion')], default='ingrese un departamento', max_length=80),
        ),
        migrations.AddField(
            model_name='observations',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 3, 25)),
        ),
        migrations.AddField(
            model_name='observations',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 2, 23)),
        ),
    ]
