# Generated by Django 5.2.8 on 2026-02-24 19:21

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_observations_departament_observations_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='end_date',
            field=models.DateField(default=app.models.Observations.default_end_date),
        ),
        migrations.AlterField(
            model_name='observations',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
