# Generated by Django 5.2.8 on 2026-03-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_observations_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observations',
            name='close_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='observations',
            name='origin',
            field=models.CharField(choices=[('Auditoria interna', 'Auditoria interna'), ('Auditoria externa', 'auditoria externa')], default='Elegir origen', max_length=100),
        ),
        migrations.AlterField(
            model_name='observations',
            name='standart',
            field=models.CharField(choices=[('ISO 9001: 2015', 'ISO 9001:2015'), ('Norma Covenin 30', 'Norma Covenin 30'), ('PDVSA EM 30-01V01', 'PDVSA EM 30-01V01')], default='Iniciada', max_length=100),
        ),
        migrations.AlterField(
            model_name='observations',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
