# Generated by Django 5.2.8 on 2026-03-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_observations_close_note_observations_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observations',
            name='file_path',
            field=models.CharField(blank=True, help_text='Ruta o URL del archivo (local, compartido o Google Drive)', max_length=400, null=True),
        ),
    ]
