# Generated by Django 5.2.8 on 2026-05-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_observations_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
